export interface DrugDetailedInfo {
  id: string;
  schedule: string;
  drugClass: string;
  streetSlang: string[];
  heatImpact: 'Extreme' | 'High' | 'Moderate' | 'Low';
  customsRisk: 'Severe' | 'High' | 'Moderate' | 'Low';
  administration: string;
  topProducerCities: string[];
  topConsumerCities: string[];
  clinicalEffects: string;
}

export const DRUG_DETAILS_MAP: Record<string, DrugDetailedInfo> = {
  cocaine: {
    id: 'cocaine',
    schedule: 'Schedule II (High Abuse Potential)',
    drugClass: 'Tropane Alkaloid / Central Nervous System Stimulant',
    streetSlang: ['Blow', 'Snow', 'Yeyo', 'Nose Candy', 'White Lady'],
    heatImpact: 'Extreme',
    customsRisk: 'Severe',
    administration: 'Insufflation (Nasal), IV Injection, Mucosal',
    topProducerCities: ['Bogotá', 'Medellín', 'Tijuana'],
    topConsumerCities: ['Tokyo', 'Zurich', 'London', 'New York'],
    clinicalEffects: 'Intense dopamine reuptake inhibition, extreme euphoria, hyper-vigilance, and tachycardia.',
  },
  heroin: {
    id: 'heroin',
    schedule: 'Schedule I (Prohibited Narcotics)',
    drugClass: 'Semisynthetic Diacetylated Opioid Analgesic',
    streetSlang: ['Smack', 'Horse', 'Black Tar', 'Brown Sugar', 'Chiva'],
    heatImpact: 'Extreme',
    customsRisk: 'Severe',
    administration: 'IV Injection, Subcutaneous, Insufflation',
    topProducerCities: ['Bangkok', 'Hong Kong', 'Bogotá'],
    topConsumerCities: ['New York', 'London', 'Frankfurt', 'Sydney'],
    clinicalEffects: 'Rapid activation of mu-opioid receptors, profound analgesia, dreamlike sedation, respiratory depression.',
  },
  crack: {
    id: 'crack',
    schedule: 'Schedule II (Freebase Derivative)',
    drugClass: 'Pyrolyzed Freebase Cocaine Alkaloid',
    streetSlang: ['Rock', 'Base', 'Grit', 'Hard', 'Hail'],
    heatImpact: 'High',
    customsRisk: 'High',
    administration: 'Inhalation (Pyrolysis / Glass Pipe)',
    topProducerCities: ['Miami', 'Tijuana', 'Los Angeles'],
    topConsumerCities: ['Chicago', 'New York', 'London'],
    clinicalEffects: 'Instantaneous 5-to-10 minute intense euphoric rush followed by rapid dysphoric crash and intense cravings.',
  },
  ice: {
    id: 'ice',
    schedule: 'Schedule II (Controlled Stimulant)',
    drugClass: 'd-Methamphetamine Hydrochloride Shards',
    streetSlang: ['Crystal', 'Glass', 'Shards', 'Tina', 'Chalk'],
    heatImpact: 'High',
    customsRisk: 'High',
    administration: 'Inhalation, Insufflation, IV Injection',
    topProducerCities: ['Tijuana', 'Los Angeles', 'Hong Kong'],
    topConsumerCities: ['Sydney', 'Tokyo', 'Frankfurt'],
    clinicalEffects: 'Massive norepinephrine and dopamine release, extended 12-hour wakefulness, hyperthermia, neurotoxicity.',
  },
  pcp: {
    id: 'pcp',
    schedule: 'Schedule II (Dissociative Anesthetic)',
    drugClass: 'Arylcyclohexylamine Dissociative',
    streetSlang: ['Angel Dust', 'Wet', 'Ozone', 'Sherm', 'Embalming Fluid'],
    heatImpact: 'Moderate',
    customsRisk: 'Moderate',
    administration: 'Smoking (dipped joints/blunts), Insufflation',
    topProducerCities: ['Los Angeles', 'Chicago', 'Tijuana'],
    topConsumerCities: ['New York', 'Berlin', 'London'],
    clinicalEffects: 'NMDA receptor antagonism, severe depersonalization, analgesic numbness, erratic unpredictable aggression.',
  },
  opium: {
    id: 'opium',
    schedule: 'Schedule II (Natural Opiate Latex)',
    drugClass: 'Natural Phenanthrene Alkaloid Resin',
    streetSlang: ['Tar', 'Dope', 'Poppy Latex', 'Midnight Oil', 'Big O'],
    heatImpact: 'Moderate',
    customsRisk: 'High',
    administration: 'Vaporization, Oral Ingestion, Sublingual',
    topProducerCities: ['Bangkok', 'Hong Kong', 'Johannesburg'],
    topConsumerCities: ['Zurich', 'London', 'Tokyo'],
    clinicalEffects: 'Mild euphoric analgesic sedation, smooth smooth-muscle relaxation, pupillary constriction.',
  },
  hashish: {
    id: 'hashish',
    schedule: 'Schedule I (Concentrated Cannabinoid)',
    drugClass: 'Compressed Trichome Resin Complex',
    streetSlang: ['Charas', 'Blonde Moroccan', 'Pollen', 'Bubble Hash', 'Slate'],
    heatImpact: 'Low',
    customsRisk: 'High',
    administration: 'Inhalation (Pipes, Vaporizers, Mixed Joints)',
    topProducerCities: ['Amsterdam', 'Johannesburg', 'Rio de Janeiro'],
    topConsumerCities: ['Tokyo', 'Zurich', 'Sydney', 'London'],
    clinicalEffects: 'Potent CB1/CB2 receptor activation, sensory intensification, heavy motor sedation, relaxation.',
  },
  krokodil: {
    id: 'krokodil',
    schedule: 'Schedule I (Crude Desomorphine Synthesis)',
    drugClass: 'Crude Morphine Analogue with Toxic Byproducts',
    streetSlang: ['Crocodil', 'Russian Dope', 'Poor Man Heroin', 'Zombie Drug'],
    heatImpact: 'High',
    customsRisk: 'Moderate',
    administration: 'IV Injection (Crude Solution)',
    topProducerCities: ['Moscow', 'Berlin', 'Frankfurt'],
    topConsumerCities: ['London', 'New York', 'Chicago'],
    clinicalEffects: 'Short-acting extreme sedation; extreme tissue necrosis, phlebitis, and gangrenous skin ulcerations.',
  },
  lsd: {
    id: 'lsd',
    schedule: 'Schedule I (Non-Addictive Hallucinogen)',
    drugClass: 'Semisynthetic Ergoline Psychedelic',
    streetSlang: ['Acid', 'Blotter', 'Tabs', 'Lucy', 'California Sunshine'],
    heatImpact: 'Low',
    customsRisk: 'Low',
    administration: 'Sublingual, Oral (Perforated Blotter Paper)',
    topProducerCities: ['Amsterdam', 'Berlin', 'Seattle'],
    topConsumerCities: ['Tokyo', 'Sydney', 'London', 'Zurich'],
    clinicalEffects: 'Potent 5-HT2A receptor agonism, geometric synesthesia, cognitive restructuring, 10-to-14 hour perceptual shifts.',
  },
  morphine: {
    id: 'morphine',
    schedule: 'Schedule II (Prescription Analgesic)',
    drugClass: 'Natural Phenanthrene Opiate Analgesic',
    streetSlang: ['M-15s', 'Morph', 'Miss Emma', 'Blue Angels', 'State Dope'],
    heatImpact: 'Moderate',
    customsRisk: 'Moderate',
    administration: 'Oral Tablets, IV Injection',
    topProducerCities: ['Berlin', 'Zurich', 'Frankfurt'],
    topConsumerCities: ['New York', 'Tokyo', 'Sydney'],
    clinicalEffects: 'Targeted central pain suppression, profound physical warmth, drowsiness, and anxiolysis.',
  },
  peyote: {
    id: 'peyote',
    schedule: 'Schedule I (Protected Botanical)',
    drugClass: 'Natural Phenethylamine Mescaline Cactus',
    streetSlang: ['Buttons', 'Mescal', 'Topi', 'Divine Herb'],
    heatImpact: 'Low',
    customsRisk: 'Moderate',
    administration: 'Oral (Masticated Dried Cactus Buttons)',
    topProducerCities: ['Tijuana', 'Miami', 'Rio de Janeiro'],
    topConsumerCities: ['Berlin', 'Amsterdam', 'London'],
    clinicalEffects: 'Visual geometric intensification, empathic introspection, auditory enhancement, tactile warmth.',
  },
  fentanyl: {
    id: 'fentanyl',
    schedule: 'Schedule II (Ultra-Potent Synthetic Cut)',
    drugClass: 'Synthetic Phenylpiperidine Opioid',
    streetSlang: ['China White', 'Apache', 'Murder 8', 'Dance Fever', 'Drop Dead'],
    heatImpact: 'Extreme',
    customsRisk: 'Severe',
    administration: 'Transdermal, Insufflation, Smoked Pressed Pills',
    topProducerCities: ['Tijuana', 'Hong Kong', 'Los Angeles'],
    topConsumerCities: ['New York', 'Chicago', 'Seattle', 'London'],
    clinicalEffects: '50-100x potency of morphine; extreme rapid respiratory arrest risk with acute analgesic anesthesia.',
  },
  speed: {
    id: 'speed',
    schedule: 'Schedule II (Prescription Psychostimulant)',
    drugClass: 'Racemic Amphetamine Sulfate',
    streetSlang: ['Whizz', 'Uppers', 'Bennie', 'Fast Lane', 'Sulphate'],
    heatImpact: 'Low',
    customsRisk: 'Moderate',
    administration: 'Oral, Insufflation, Ingestion',
    topProducerCities: ['Frankfurt', 'Amsterdam', 'Berlin'],
    topConsumerCities: ['London', 'New York', 'Tokyo'],
    clinicalEffects: 'Sustained endurance boost, mental alertness, suppressed appetite, sympathetic nervous arousal.',
  },
  tranq: {
    id: 'tranq',
    schedule: 'Unscheduled / Veterinary Schedule IV',
    drugClass: 'Non-Opioid Alpha-2 Adrenergic Agonist',
    streetSlang: ['Sleep Cut', 'Horse Tranquilizer', 'Philly Dope', 'Zombie Juice'],
    heatImpact: 'High',
    customsRisk: 'Moderate',
    administration: 'Mixed Street Injection, Smoked Adulterant',
    topProducerCities: ['Tijuana', 'Miami', 'Chicago'],
    topConsumerCities: ['New York', 'London', 'Frankfurt'],
    clinicalEffects: 'Profound motor paralysis, deep arterial hypotension, prolonged unconsciousness, persistent necrotic lesions.',
  },
  mda: {
    id: 'mda',
    schedule: 'Schedule I (Club Entactogen)',
    drugClass: 'Substituted Amphetamine & Phenethylamine',
    streetSlang: ['Sally', 'The Love Drug', 'Hug Drug', 'Mandy'],
    heatImpact: 'Moderate',
    customsRisk: 'Moderate',
    administration: 'Oral Capsule, Insufflation',
    topProducerCities: ['Amsterdam', 'Berlin', 'Miami'],
    topConsumerCities: ['Tokyo', 'London', 'Sydney'],
    clinicalEffects: 'Profound social empathy, heightened tactile sensory acuity, mild visual patterning, cardiovascular stimulation.',
  },
  mushrooms: {
    id: 'mushrooms',
    schedule: 'Schedule I (Tryptamine Prodrug)',
    drugClass: 'Natural Indole Alkaloid Tryptamine',
    streetSlang: ['Shrooms', 'Magic Caps', 'Boomers', 'Flesh of the Gods', 'Blue Angels'],
    heatImpact: 'Low',
    customsRisk: 'Moderate',
    administration: 'Oral Ingestion (Dried Caps, Brewed Tea)',
    topProducerCities: ['Seattle', 'Amsterdam', 'Rio de Janeiro'],
    topConsumerCities: ['London', 'Tokyo', 'Zurich'],
    clinicalEffects: '5-HT2A agonism yielding emotional openness, visual fluidity, temporal distortion, and spiritual experiences.',
  },
  pot: {
    id: 'pot',
    schedule: 'Schedule I / Decriminalized Regionally',
    drugClass: 'Natural Terpenoid Cannabinoid Flora',
    streetSlang: ['Weed', 'Bud', 'Herb', 'Mary Jane', 'Ganja', 'Skunk'],
    heatImpact: 'Low',
    customsRisk: 'High',
    administration: 'Inhalation (Combustion/Vaporization), Oral Edibles',
    topProducerCities: ['Seattle', 'Los Angeles', 'Amsterdam'],
    topConsumerCities: ['Tokyo', 'Dubai', 'Sydney', 'London'],
    clinicalEffects: 'Mild euphoria, appetite stimulation, relaxation, altered sensory perception, short-term memory inhibition.',
  },
  special_k: {
    id: 'special_k',
    schedule: 'Schedule III (Veterinary Dissociative)',
    drugClass: 'Arylcyclohexylamine Dissociative Anesthetic',
    streetSlang: ['K', 'Ket', 'Kit-Kat', 'Super C', 'Special K'],
    heatImpact: 'Low',
    customsRisk: 'Moderate',
    administration: 'Insufflation (Crushed Crystals), Intramuscular',
    topProducerCities: ['London', 'Frankfurt', 'Amsterdam'],
    topConsumerCities: ['Tokyo', 'New York', 'Sydney'],
    clinicalEffects: 'Dissociative anesthesia, sensory detachment ("K-Hole"), auditory distortion, analgesic numbness.',
  },
  ecstasy: {
    id: 'ecstasy',
    schedule: 'Schedule I (Synthetic Empathogen)',
    drugClass: 'Ring-Substituted Phenethylamine Entactogen',
    streetSlang: ['E', 'XTC', 'Molly', 'Rolls', 'Disco Biscuits', 'Pills'],
    heatImpact: 'Moderate',
    customsRisk: 'High',
    administration: 'Oral (Pressed Stamp Tablets)',
    topProducerCities: ['Amsterdam', 'Frankfurt', 'Berlin'],
    topConsumerCities: ['London', 'Tokyo', 'Sydney', 'New York'],
    clinicalEffects: 'Massive serotonin release, profound emotional bonding, tactile euphoria, energetic stimulation, trismus.',
  },
  kat: {
    id: 'kat',
    schedule: 'Schedule I / Traditional Commodity',
    drugClass: 'Natural Monoamine Alkaloid Cathinone',
    streetSlang: ['Qat', 'Chat', 'Miraa', 'Abyssinian Tea', 'Arabian Tea'],
    heatImpact: 'Low',
    customsRisk: 'Moderate',
    administration: 'Buccal Mastication (Chewing Fresh Leaves)',
    topProducerCities: ['Johannesburg', 'Dubai', 'Rio de Janeiro'],
    topConsumerCities: ['London', 'Frankfurt', 'Berlin'],
    clinicalEffects: 'Mild stimulant euphoria, heightened conversation, moderate mental stimulation, mild appetite suppression.',
  },
  super_soldier_serum: {
    id: 'super_soldier_serum',
    schedule: 'Classified / Military Black-Ops Restricted',
    drugClass: 'Synthetic Nootropic-Combat Stimulant Matrix',
    streetSlang: ['Compound-Z', 'Valkyrie', 'Titan', 'Zero-Hour', 'Blue Ghost'],
    heatImpact: 'Extreme',
    customsRisk: 'Severe',
    administration: 'IV Injection / Sublingual Dropper',
    topProducerCities: ['Berlin', 'Seoul', 'Tokyo'],
    topConsumerCities: ['New York', 'London', 'Zurich', 'Singapore'],
    clinicalEffects: 'Surge in cognitive processing velocity, extreme adrenaline saturation, complete pain suppression, hyper-reflexes.',
  },
  carfentanil: {
    id: 'carfentanil',
    schedule: 'Schedule II (Veterinary Ultra-Opioid)',
    drugClass: '4-Carbomethoxyfentanyl Heavy Analgesic',
    streetSlang: ['Wildnil', 'Elephant Dust', 'Drop Dead', 'Gray Death', 'C-100'],
    heatImpact: 'Extreme',
    customsRisk: 'Severe',
    administration: 'Transdermal Cut / Microgram Powder / IV',
    topProducerCities: ['Tijuana', 'Hong Kong', 'Shanghai'],
    topConsumerCities: ['Chicago', 'Detroit', 'New York', 'Vancouver'],
    clinicalEffects: 'Instantaneous profound mu-opioid receptor lockdown. 10,000x morphine potency, fatal respiratory arrest risk within seconds.',
  },
  dmt: {
    id: 'dmt',
    schedule: 'Schedule I (Endogenous Tryptamine)',
    drugClass: 'Freebase N,N-Dimethyltryptamine Crystals',
    streetSlang: ['Spirit Molecule', 'Dimitri', 'Businessman Trip', 'Changa', 'Fantasia'],
    heatImpact: 'Moderate',
    customsRisk: 'Moderate',
    administration: 'Vaporization / Inhalation (Freebase Pipe)',
    topProducerCities: ['Rio de Janeiro', 'São Paulo', 'Amsterdam'],
    topConsumerCities: ['San Francisco', 'London', 'Ibiza', 'Berlin'],
    clinicalEffects: 'Instantaneous non-physical visual breakthrough, profound time-dilation, hyper-dimensional visual hallucinations.',
  },
  oxycodone: {
    id: 'oxycodone',
    schedule: 'Schedule II (Prescription Semisynthetic Opioid)',
    drugClass: 'Oxycodone Hydrochloride Extended-Release',
    streetSlang: ['Oxy 80', 'Percs', 'Beans', 'Killers', 'Blues', 'Hillbilly Heroin'],
    heatImpact: 'Moderate',
    customsRisk: 'High',
    administration: 'Oral Tablet / Crushed Insufflation',
    topProducerCities: ['Miami', 'Chicago', 'Frankfurt'],
    topConsumerCities: ['New York', 'Los Angeles', 'Toronto', 'Sydney'],
    clinicalEffects: 'High-affinity oral opioid euphoria, deep pain eradication, warm sedation, rapid physical dependence.',
  },
  codeine: {
    id: 'codeine',
    schedule: 'Schedule V (Antitussive / Phenanthrene Alkaloid)',
    drugClass: 'Promethazine-Codeine Cough Syrup Emulsion',
    streetSlang: ['Lean', 'Purple Drank', 'Sizzurp', 'Dirty Sprite', 'Texas Tea', 'Barre'],
    heatImpact: 'Low',
    customsRisk: 'Moderate',
    administration: 'Oral Solution (Soda Dilution / Styrofoam Cup)',
    topProducerCities: ['Houston', 'Atlanta', 'Miami'],
    topConsumerCities: ['Los Angeles', 'New York', 'London', 'Paris'],
    clinicalEffects: 'Gentle dreamy sedation, central nervous system relaxation, mild motor sluggishness, sustained calming euphoria.',
  },
};

export function getDrugDetails(drugId: string): DrugDetailedInfo {
  return (
    DRUG_DETAILS_MAP[drugId.toLowerCase()] ?? {
      id: drugId,
      schedule: 'Schedule I (Underworld Controlled)',
      drugClass: 'Classified Illicit Narcotic',
      streetSlang: ['Contraband', 'Product', 'Package'],
      heatImpact: 'Moderate',
      customsRisk: 'Moderate',
      administration: 'Street Distribution',
      topProducerCities: ['Bogotá', 'Tijuana'],
      topConsumerCities: ['New York', 'London', 'Tokyo'],
      clinicalEffects: 'High-margin illicit contraband subject to regional price volatility.',
    }
  );
}
